-- ============================================================================
--  EduLink — مخطط قاعدة البيانات (Database Schema)
--  الملف الوحيد لكل تغييرات البيانات: جداول، أعمدة، فهارس، قيود.
-- ============================================================================
--
--  ⚠️ قواعد إلزامية (لا تُخالَف):
--
--   1) كل تغيير في قاعدة البيانات يُضاف إلى **هذا الملف نفسه** في آخر قسم
--      «إضافات جديدة». لا تُنشأ ملفات migrations منفصلة مهما كبر الملف.
--
--   2) الملف **قابل لإعادة التشغيل** (Idempotent): كل عبارة محميّة بـ IF NOT EXISTS
--      أو DROP IF EXISTS، فتشغيله مرة واحدة أو عشر مرات يعطي نفس النتيجة.
--
--   3) اسم كل جدول جديد يبدأ بـ **Edu_** ثم اسم الجدول.
--
--   4) يعمل الآن على **Supabase (PostgreSQL)**، ونسخة **SQL Server** جاهزة في
--      آخر الملف (مُعلَّقة) للانتقال المستقبلي إلى سيرفر الشركة.
--
--
--  طريقة التشغيل على Supabase:
--     Supabase Dashboard → SQL Editor → New query → الصق الملف كاملًا → Run
--
--
--  ⚠️ ملاحظة مهمة عن أسماء الجداول:
--     الأسماء مكتوبة بين علامتي تنصيص "Edu_Users" للحفاظ على حالة الأحرف
--     (PascalCase) كما ستكون على SQL Server. ولهذا يجب دائمًا كتابة الاسم
--     بين علامتي تنصيص في استعلامات PostgreSQL:
--         SELECT * FROM "Edu_Users";          ✅
--         SELECT * FROM Edu_Users;            ❌ (يبحث عن edu_users)
--
-- ============================================================================


-- ============================================================================
--  أعمدة الحساب المشتركة (مكرّرة نصًّا في كل جدول حساب: Users / Students / Parents)
-- ============================================================================
--
--  name          : الاسم الكامل للشخص
--  email         : البريد الإلكتروني — فريد، ويُخزَّن بحروف صغيرة (lowercase)
--  password      : **هاش** كلمة المرور — لا يُخزَّن النص الصريح أبدًا.
--                  التجزئة في طبقة التطبيق (bcrypt / PBKDF2) لأن SQL Server
--                  لا يملك دوال تجزئة مكافئة لـ pgcrypto.
--  token         : توكن الدخول الحالي — NULL يعني لا توجد جلسة فعّالة
--  states        : 0 = الحساب غير ظاهر للناس | 1 = ظاهر
--  access        : 0 = غير مفعّل، لا يستطيع الدخول للمنصة إطلاقًا | 1 = مفعّل
--  img_url       : رابط صورة الحساب إن وُجدت — NULL يعني لا توجد صورة
--  notifications : هل إنشاء هذا الحساب **أُرسل كإشعار للكل** أم لا
--                  0 = أُنشئ ولم يُرسل إشعار للكل | 1 = أُرسل إشعار للكل
--  created_at/updated_at : وupdated_at يُحدَّث تلقائيًا بتريجر
--
-- ============================================================================


-- ============================================================================
--  1) Edu_Users — موظفو المنصة (المدرسون، المشرفون، المديرون، الأونر)
-- ============================================================================
--
--  role : 0 = مدرس | 1 = مشرف | 2 = مدير | 3 = أونر
--         (يبدأ من 0 للمدرس ويزيد رقمًا مع كل دور أعلى)
--
-- ============================================================================

CREATE TABLE IF NOT EXISTS "Edu_Users" (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255),
    email         VARCHAR(255) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    role          SMALLINT     NOT NULL DEFAULT 0,
    token         TEXT,
    states        SMALLINT     NOT NULL DEFAULT 0,
    access        SMALLINT     NOT NULL DEFAULT 0,
    img_url       TEXT,
    notifications SMALLINT     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_edu_users               PRIMARY KEY (id),
    CONSTRAINT uq_edu_users_email         UNIQUE (email),
    CONSTRAINT ck_edu_users_role          CHECK (role >= 0),
    CONSTRAINT ck_edu_users_states        CHECK (states IN (0, 1)),
    CONSTRAINT ck_edu_users_access        CHECK (access IN (0, 1)),
    CONSTRAINT ck_edu_users_notifications CHECK (notifications IN (0, 1))
);

COMMENT ON TABLE  "Edu_Users"               IS 'موظفو المنصة: مدرس، مشرف، مدير، أونر';
COMMENT ON COLUMN "Edu_Users".name          IS 'الاسم الكامل';
COMMENT ON COLUMN "Edu_Users".role          IS '0=مدرس, 1=مشرف, 2=مدير, 3=أونر';
COMMENT ON COLUMN "Edu_Users".notifications IS 'هل إنشاء هذا المستخدم أُرسل كإشعار للكل: 0=لا, 1=نعم';

CREATE INDEX IF NOT EXISTS "ix_Edu_Users_token" ON "Edu_Users" (token);
CREATE INDEX IF NOT EXISTS "ix_Edu_Users_role"  ON "Edu_Users" (role);


-- ============================================================================
--  2) Edu_Students — الطلاب
-- ============================================================================
--
--  لا يوجد عمود role: كل صف هنا طالب.
--
-- ============================================================================

CREATE TABLE IF NOT EXISTS "Edu_Students" (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255),
    email         VARCHAR(255) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    token         TEXT,
    states        SMALLINT     NOT NULL DEFAULT 0,
    access        SMALLINT     NOT NULL DEFAULT 0,
    img_url       TEXT,
    notifications SMALLINT     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_edu_students               PRIMARY KEY (id),
    CONSTRAINT uq_edu_students_email         UNIQUE (email),
    CONSTRAINT ck_edu_students_states        CHECK (states IN (0, 1)),
    CONSTRAINT ck_edu_students_access        CHECK (access IN (0, 1)),
    CONSTRAINT ck_edu_students_notifications CHECK (notifications IN (0, 1))
);

COMMENT ON TABLE  "Edu_Students"               IS 'طلاب المنصة';
COMMENT ON COLUMN "Edu_Students".name          IS 'الاسم الكامل';
COMMENT ON COLUMN "Edu_Students".notifications IS 'هل إنشاء هذا الطالب أُرسل كإشعار للكل: 0=لا, 1=نعم';

CREATE INDEX IF NOT EXISTS "ix_Edu_Students_token" ON "Edu_Students" (token);


-- ============================================================================
--  3) Edu_Parents — أولياء الأمور
-- ============================================================================
--
--  نفس أعمدة Edu_Students تمامًا (بدون role).
--
-- ============================================================================

CREATE TABLE IF NOT EXISTS "Edu_Parents" (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255),
    email         VARCHAR(255) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    token         TEXT,
    states        SMALLINT     NOT NULL DEFAULT 0,
    access        SMALLINT     NOT NULL DEFAULT 0,
    img_url       TEXT,
    notifications SMALLINT     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_edu_parents               PRIMARY KEY (id),
    CONSTRAINT uq_edu_parents_email         UNIQUE (email),
    CONSTRAINT ck_edu_parents_states        CHECK (states IN (0, 1)),
    CONSTRAINT ck_edu_parents_access        CHECK (access IN (0, 1)),
    CONSTRAINT ck_edu_parents_notifications CHECK (notifications IN (0, 1))
);

COMMENT ON TABLE  "Edu_Parents"               IS 'أولياء أمور الطلاب';
COMMENT ON COLUMN "Edu_Parents".name          IS 'الاسم الكامل';
COMMENT ON COLUMN "Edu_Parents".notifications IS 'هل إنشاء ولي الأمر أُرسل كإشعار للكل: 0=لا, 1=نعم';

CREATE INDEX IF NOT EXISTS "ix_Edu_Parents_token" ON "Edu_Parents" (token);


-- ============================================================================
--  4) Edu_Relations — جدول الربط بين الطالب وولي الأمر (علاقة متعدد لمتعدد)
-- ============================================================================
--
--  لماذا جدول منفصل؟ لأن العلاقة **متعدد لمتعدد**:
--     • ولي أمر واحد قد يكون له أكثر من طالب (أخوان على المنصة)
--     • الطالب الواحد قد يكون له أكثر من ولي أمر (الأب والأم مثلًا)
--  ولو وضعنا parent_id داخل Edu_Students لقبلنا ولي أمر واحد فقط، ولو وضعنا
--  student_id داخل Edu_Parents لقبلنا طالبًا واحدًا فقط.
--
--  ⚠️ لا يوجد عمود name في هذا الجدول — فهو جدول ربط وليس كيانًا له اسم.
--
--  relation   : صلة القرابة بين ولي الأمر والطالب
--               0 = أب | 1 = أم | 2 = وصي / ولي أمر | 3 = أخرى
--  is_primary : 0 = ولي أمر عادي | 1 = **ولي الأمر الأساسي** (أول من يُتواصل معه)
--               ومقيّد بفهرس فريد جزئي: **ولي أمر أساسي واحد فقط لكل طالب**
--  states     : 0 = الرابط موقوف (لا يُحتسب) | 1 = فعّال
--               لاحظ: الافتراضي هنا **1** بخلاف جداول الحسابات (افتراضيها 0)،
--               لأن الرابط يُنشئه المشرف فيكون فعّالًا فورًا.
--
--  ⚠️ لا يوجد عمود notifications هنا عن قصد: الإنشاء هنا ربطٌ بين سجلين
--     وليس حدثًا يُعلَن للكل. (لو أردت العمود للتوحيد، قوله.)
--
-- ============================================================================

CREATE TABLE IF NOT EXISTS "Edu_Relations" (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    student_id BIGINT      NOT NULL,
    parent_id  BIGINT      NOT NULL,
    relation   SMALLINT    NOT NULL DEFAULT 0,
    is_primary SMALLINT    NOT NULL DEFAULT 0,
    states     SMALLINT    NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_edu_relations          PRIMARY KEY (id),
    CONSTRAINT fk_edu_relations_student  FOREIGN KEY (student_id) REFERENCES "Edu_Students" (id) ON DELETE CASCADE,
    CONSTRAINT fk_edu_relations_parent   FOREIGN KEY (parent_id)  REFERENCES "Edu_Parents" (id)  ON DELETE CASCADE,
    CONSTRAINT uq_edu_relations_pair     UNIQUE (student_id, parent_id),
    CONSTRAINT ck_edu_relations_relation CHECK (relation IN (0, 1, 2, 3)),
    CONSTRAINT ck_edu_relations_primary  CHECK (is_primary IN (0, 1)),
    CONSTRAINT ck_edu_relations_states   CHECK (states IN (0, 1))
);

COMMENT ON TABLE  "Edu_Relations"            IS 'ربط الطلاب بأولياء أمورهم (متعدد لمتعدد)';
COMMENT ON COLUMN "Edu_Relations".relation   IS '0=أب, 1=أم, 2=وصي/ولي أمر, 3=أخرى';
COMMENT ON COLUMN "Edu_Relations".is_primary IS '1 = ولي الأمر الأساسي (واحد فقط لكل طالب)';
COMMENT ON COLUMN "Edu_Relations".states     IS '0=الرابط موقوف, 1=فعّال';

-- فهارس الاتجاهين: من الطالب لأولياء أمره، ومن ولي الأمر لأبنائه
CREATE INDEX IF NOT EXISTS "ix_Edu_Relations_student" ON "Edu_Relations" (student_id);
CREATE INDEX IF NOT EXISTS "ix_Edu_Relations_parent"  ON "Edu_Relations" (parent_id);

-- ولي أمر أساسي واحد فقط لكل طالب (فهرس فريد جزئي — مدعوم في المحرّكين)
CREATE UNIQUE INDEX IF NOT EXISTS "ux_Edu_Relations_one_primary"
    ON "Edu_Relations" (student_id)
    WHERE is_primary = 1;


-- ============================================================================
--  دالة تحديث updated_at (عامة لكل الجداول)
-- ============================================================================

CREATE OR REPLACE FUNCTION "Edu_SetUpdatedAt"() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "trg_Edu_Users_updated_at" ON "Edu_Users";
CREATE TRIGGER "trg_Edu_Users_updated_at"
    BEFORE UPDATE ON "Edu_Users"
    FOR EACH ROW EXECUTE FUNCTION "Edu_SetUpdatedAt"();

DROP TRIGGER IF EXISTS "trg_Edu_Students_updated_at" ON "Edu_Students";
CREATE TRIGGER "trg_Edu_Students_updated_at"
    BEFORE UPDATE ON "Edu_Students"
    FOR EACH ROW EXECUTE FUNCTION "Edu_SetUpdatedAt"();

DROP TRIGGER IF EXISTS "trg_Edu_Parents_updated_at" ON "Edu_Parents";
CREATE TRIGGER "trg_Edu_Parents_updated_at"
    BEFORE UPDATE ON "Edu_Parents"
    FOR EACH ROW EXECUTE FUNCTION "Edu_SetUpdatedAt"();

DROP TRIGGER IF EXISTS "trg_Edu_Relations_updated_at" ON "Edu_Relations";
CREATE TRIGGER "trg_Edu_Relations_updated_at"
    BEFORE UPDATE ON "Edu_Relations"
    FOR EACH ROW EXECUTE FUNCTION "Edu_SetUpdatedAt"();


-- ============================================================================
--  5) إضافات جديدة (كل تعديل قادم يُضاف هنا بالترتيب)
-- ============================================================================
--
--  اكتب الإضافة بنفس النمط:
--     ALTER TABLE "Edu_X" ADD COLUMN IF NOT EXISTS ... ;      -- عمود جديد
--     CREATE TABLE IF NOT EXISTS "Edu_X" ( ... );             -- جدول جديد
--     CREATE INDEX IF NOT EXISTS ... ;                        -- فهرس جديد
--
--  ولا تحذف أي شيء من الأعلى — الملف تراكمي.
--
-- ----------------------------------------------------------------------------
--  [2026-09-11] (1) إعادة تسمية جدول الربط: Edu_StudentParents → Edu_Relations
--
--  الجدول أعلاه مُعرَّف باسمه الجديد. والسطر التالي يحذف الاسم القديم إن كان
--  قد أُنشئ من تشغيل سابق للملف. (الجدول كان فارغًا — لا يوجد backend بعد.)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS "Edu_StudentParents";

-- ----------------------------------------------------------------------------
--  [2026-09-11] (2) إضافة العمود img_url إلى Edu_Users
--
--  موجود بالفعل في تعريف الجدول أعلى الملف، والسطر التالي يضمن إضافته أيضًا
--  لقواعد بيانات أُنشئت قبل هذا التعديل.
-- ----------------------------------------------------------------------------
ALTER TABLE "Edu_Users" ADD COLUMN IF NOT EXISTS img_url TEXT;

-- ----------------------------------------------------------------------------
--  [2026-09-11] (3) إضافة العمود name إلى جداول الحسابات الثلاثة
--
--  موجود بالفعل في تعريفات الجداول أعلى الملف، والسطورة التالية تضمن إضافته
--  لقواعد بيانات أُنشئت قبل التعديل.
--  ⚠️ جدول الربط "Edu_Relations" **مستثنى** — لا عمود name فيه.
-- ----------------------------------------------------------------------------
ALTER TABLE "Edu_Users"    ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE "Edu_Students" ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE "Edu_Parents"  ADD COLUMN IF NOT EXISTS name VARCHAR(255);

-- ============================================================================



-- ============================================================================
-- ============================================================================
--  نسخة SQL Server — للانتقال المستقبلي إلى سيرفر الشركة
--  (مُعلَّقة بالكامل. لا تُشغَّل على Supabase.)
--
--  عند الانتقال: افتح الملف، انسخ قسم SQL Server في نافذة استعلام جديدة،
--  وأزل التعليق. الفروق بين المحرّكين محصورة في:
--     • المفتاح التلقائي : IDENTITY(1,1)        بدل  GENERATED BY DEFAULT AS IDENTITY
--     • نوع الوقت        : DATETIME2            بدل  TIMESTAMPTZ
--     • النص الطويل      : NVARCHAR(MAX)        بدل  TEXT
--     • القيم الافتراضية : CONSTRAINT ... DEFAULT بدل DEFAULT المضمّن
--     • حماية الإنشاء    : IF OBJECT_ID(...) IS NULL بدل CREATE TABLE IF NOT EXISTS
--     • إضافة عمود       : IF COL_LENGTH(...) IS NULL بدل ADD COLUMN IF NOT EXISTS
--     • حذف جدول         : IF OBJECT_ID(...) IS NOT NULL DROP TABLE بدل DROP TABLE IF EXISTS
--     • تحديث updated_at : تريجر AFTER UPDATE لكل جدول بدل تريجر BEFORE UPDATE
--          (وكل ما عدا ذلك — القيود والفهارس وأسماء الأعمدة — متطابق)
-- ============================================================================
-- ============================================================================

/*
-- ---- Edu_Users ----
IF OBJECT_ID('Edu_Users', 'U') IS NULL
BEGIN
    CREATE TABLE Edu_Users (
        id            BIGINT        IDENTITY(1,1) NOT NULL,
        name          NVARCHAR(255) NULL,
        email         NVARCHAR(255) NOT NULL,
        password      NVARCHAR(255) NOT NULL,
        role          SMALLINT      NOT NULL CONSTRAINT df_edu_users_role          DEFAULT 0,
        token         NVARCHAR(MAX) NULL,
        states        SMALLINT      NOT NULL CONSTRAINT df_edu_users_states        DEFAULT 0,
        access        SMALLINT      NOT NULL CONSTRAINT df_edu_users_access        DEFAULT 0,
        img_url       NVARCHAR(MAX) NULL,
        notifications SMALLINT      NOT NULL CONSTRAINT df_edu_users_notifications DEFAULT 0,
        created_at    DATETIME2     NOT NULL CONSTRAINT df_edu_users_created_at    DEFAULT SYSUTCDATETIME(),
        updated_at    DATETIME2     NOT NULL CONSTRAINT df_edu_users_updated_at    DEFAULT SYSUTCDATETIME(),

        CONSTRAINT pk_edu_users               PRIMARY KEY (id),
        CONSTRAINT uq_edu_users_email         UNIQUE (email),
        CONSTRAINT ck_edu_users_role          CHECK (role >= 0),
        CONSTRAINT ck_edu_users_states        CHECK (states IN (0, 1)),
        CONSTRAINT ck_edu_users_access        CHECK (access IN (0, 1)),
        CONSTRAINT ck_edu_users_notifications CHECK (notifications IN (0, 1))
    );
END
GO

-- ---- Edu_Students ----
IF OBJECT_ID('Edu_Students', 'U') IS NULL
BEGIN
    CREATE TABLE Edu_Students (
        id            BIGINT        IDENTITY(1,1) NOT NULL,
        name          NVARCHAR(255) NULL,
        email         NVARCHAR(255) NOT NULL,
        password      NVARCHAR(255) NOT NULL,
        token         NVARCHAR(MAX) NULL,
        states        SMALLINT      NOT NULL CONSTRAINT df_edu_students_states        DEFAULT 0,
        access        SMALLINT      NOT NULL CONSTRAINT df_edu_students_access        DEFAULT 0,
        img_url       NVARCHAR(MAX) NULL,
        notifications SMALLINT      NOT NULL CONSTRAINT df_edu_students_notifications DEFAULT 0,
        created_at    DATETIME2     NOT NULL CONSTRAINT df_edu_students_created_at    DEFAULT SYSUTCDATETIME(),
        updated_at    DATETIME2     NOT NULL CONSTRAINT df_edu_students_updated_at    DEFAULT SYSUTCDATETIME(),

        CONSTRAINT pk_edu_students               PRIMARY KEY (id),
        CONSTRAINT uq_edu_students_email         UNIQUE (email),
        CONSTRAINT ck_edu_students_states        CHECK (states IN (0, 1)),
        CONSTRAINT ck_edu_students_access        CHECK (access IN (0, 1)),
        CONSTRAINT ck_edu_students_notifications CHECK (notifications IN (0, 1))
    );
END
GO

-- ---- Edu_Parents ----
IF OBJECT_ID('Edu_Parents', 'U') IS NULL
BEGIN
    CREATE TABLE Edu_Parents (
        id            BIGINT        IDENTITY(1,1) NOT NULL,
        name          NVARCHAR(255) NULL,
        email         NVARCHAR(255) NOT NULL,
        password      NVARCHAR(255) NOT NULL,
        token         NVARCHAR(MAX) NULL,
        states        SMALLINT      NOT NULL CONSTRAINT df_edu_parents_states        DEFAULT 0,
        access        SMALLINT      NOT NULL CONSTRAINT df_edu_parents_access        DEFAULT 0,
        img_url       NVARCHAR(MAX) NULL,
        notifications SMALLINT      NOT NULL CONSTRAINT df_edu_parents_notifications DEFAULT 0,
        created_at    DATETIME2     NOT NULL CONSTRAINT df_edu_parents_created_at    DEFAULT SYSUTCDATETIME(),
        updated_at    DATETIME2     NOT NULL CONSTRAINT df_edu_parents_updated_at    DEFAULT SYSUTCDATETIME(),

        CONSTRAINT pk_edu_parents               PRIMARY KEY (id),
        CONSTRAINT uq_edu_parents_email         UNIQUE (email),
        CONSTRAINT ck_edu_parents_states        CHECK (states IN (0, 1)),
        CONSTRAINT ck_edu_parents_access        CHECK (access IN (0, 1)),
        CONSTRAINT ck_edu_parents_notifications CHECK (notifications IN (0, 1))
    );
END
GO

-- ---- Edu_Relations ----
IF OBJECT_ID('Edu_Relations', 'U') IS NULL
BEGIN
    CREATE TABLE Edu_Relations (
        id         BIGINT      IDENTITY(1,1) NOT NULL,
        student_id BIGINT      NOT NULL,
        parent_id  BIGINT      NOT NULL,
        relation   SMALLINT    NOT NULL CONSTRAINT df_edu_relations_relation   DEFAULT 0,
        is_primary SMALLINT    NOT NULL CONSTRAINT df_edu_relations_is_primary DEFAULT 0,
        states     SMALLINT    NOT NULL CONSTRAINT df_edu_relations_states     DEFAULT 1,
        created_at DATETIME2   NOT NULL CONSTRAINT df_edu_relations_created_at DEFAULT SYSUTCDATETIME(),
        updated_at DATETIME2   NOT NULL CONSTRAINT df_edu_relations_updated_at DEFAULT SYSUTCDATETIME(),

        CONSTRAINT pk_edu_relations          PRIMARY KEY (id),
        CONSTRAINT fk_edu_relations_student  FOREIGN KEY (student_id) REFERENCES Edu_Students (id) ON DELETE CASCADE,
        CONSTRAINT fk_edu_relations_parent   FOREIGN KEY (parent_id)  REFERENCES Edu_Parents (id)  ON DELETE CASCADE,
        CONSTRAINT uq_edu_relations_pair     UNIQUE (student_id, parent_id),
        CONSTRAINT ck_edu_relations_relation CHECK (relation IN (0, 1, 2, 3)),
        CONSTRAINT ck_edu_relations_primary  CHECK (is_primary IN (0, 1)),
        CONSTRAINT ck_edu_relations_states   CHECK (states IN (0, 1))
    );
END
GO

-- ---- الفهارس ----
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_Edu_Users_token' AND object_id = OBJECT_ID('Edu_Users'))
    CREATE INDEX ix_Edu_Users_token ON Edu_Users (token);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_Edu_Users_role' AND object_id = OBJECT_ID('Edu_Users'))
    CREATE INDEX ix_Edu_Users_role ON Edu_Users (role);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_Edu_Students_token' AND object_id = OBJECT_ID('Edu_Students'))
    CREATE INDEX ix_Edu_Students_token ON Edu_Students (token);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_Edu_Parents_token' AND object_id = OBJECT_ID('Edu_Parents'))
    CREATE INDEX ix_Edu_Parents_token ON Edu_Parents (token);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_Edu_Relations_student' AND object_id = OBJECT_ID('Edu_Relations'))
    CREATE INDEX ix_Edu_Relations_student ON Edu_Relations (student_id);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ix_Edu_Relations_parent' AND object_id = OBJECT_ID('Edu_Relations'))
    CREATE INDEX ix_Edu_Relations_parent ON Edu_Relations (parent_id);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'ux_Edu_Relations_one_primary' AND object_id = OBJECT_ID('Edu_Relations'))
    CREATE UNIQUE INDEX ux_Edu_Relations_one_primary ON Edu_Relations (student_id) WHERE is_primary = 1;
GO

-- ---- إضافات جديدة (نفس ترتيب قسم الإضافات في نسخة PostgreSQL) ----
IF OBJECT_ID('Edu_StudentParents', 'U') IS NOT NULL DROP TABLE Edu_StudentParents;
GO
IF COL_LENGTH('Edu_Users', 'img_url') IS NULL    ALTER TABLE Edu_Users    ADD img_url NVARCHAR(MAX) NULL;
IF COL_LENGTH('Edu_Users', 'name') IS NULL       ALTER TABLE Edu_Users    ADD name    NVARCHAR(255) NULL;
IF COL_LENGTH('Edu_Students', 'name') IS NULL    ALTER TABLE Edu_Students ADD name    NVARCHAR(255) NULL;
IF COL_LENGTH('Edu_Parents', 'name') IS NULL     ALTER TABLE Edu_Parents  ADD name    NVARCHAR(255) NULL;
GO

-- ---- تريجرات updated_at (في SQL Server تريجر AFTER UPDATE لكل جدول) ----
IF OBJECT_ID('trg_Edu_Users_updated_at', 'TR') IS NOT NULL DROP TRIGGER trg_Edu_Users_updated_at;
GO
CREATE TRIGGER trg_Edu_Users_updated_at ON Edu_Users AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE u SET u.updated_at = SYSUTCDATETIME()
      FROM Edu_Users AS u INNER JOIN inserted AS i ON i.id = u.id;
END
GO

IF OBJECT_ID('trg_Edu_Students_updated_at', 'TR') IS NOT NULL DROP TRIGGER trg_Edu_Students_updated_at;
GO
CREATE TRIGGER trg_Edu_Students_updated_at ON Edu_Students AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE s SET s.updated_at = SYSUTCDATETIME()
      FROM Edu_Students AS s INNER JOIN inserted AS i ON i.id = s.id;
END
GO

IF OBJECT_ID('trg_Edu_Parents_updated_at', 'TR') IS NOT NULL DROP TRIGGER trg_Edu_Parents_updated_at;
GO
CREATE TRIGGER trg_Edu_Parents_updated_at ON Edu_Parents AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE p SET p.updated_at = SYSUTCDATETIME()
      FROM Edu_Parents AS p INNER JOIN inserted AS i ON i.id = p.id;
END
GO

IF OBJECT_ID('trg_Edu_Relations_updated_at', 'TR') IS NOT NULL DROP TRIGGER trg_Edu_Relations_updated_at;
GO
CREATE TRIGGER trg_Edu_Relations_updated_at ON Edu_Relations AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE r SET r.updated_at = SYSUTCDATETIME()
      FROM Edu_Relations AS r INNER JOIN inserted AS i ON i.id = r.id;
END
GO
*/
